galaxy_info:
  role_name: deploy
  description: Launch server with app
  author: Kirill Lavrentev
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
         
