galaxy_info:
  role_name: install_minikube
  description: Install minikube
  author: Kirill Lavrentev
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: CentOS
      versions: 7
         