galaxy_info:
  role_name: preconfig
  description: Настройка сервера с нужными параметрами
  author: Kirill Lavrentev
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: CentOS
      versions: 7