---
- name: Preconfig Block for CentOS
  when: ansible_facts['distribution'] == 'CentOS'
  block:
    - name: Download Virtual Box
      get_url: 
        url: https://download.virtualbox.org/virtualbox/6.1.34/VirtualBox-6.1-6.1.34_150636_el7-2.x86_64.rpm
        dest: /tmp
        mode: 'u=rw,go=r'

    - name: Install python3 if it is not installed
      become: yes
      yum:
        name: python3, /tmp/VirtualBox-6.1-6.1.34_150636_el7-2.x86_64.rpm
        state: present